version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ../docker/mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

# Robot3:: mongodb://admin:password@localhost:27017